<%@ page import="java.util.*,com.eventbooking.model.*" %>
<%@ include file="header.jsp" %>
<% List<User> users=(List<User>)request.getAttribute("users"); List<Admin> admins=(List<Admin>)request.getAttribute("admins"); List<Event> events=(List<Event>)request.getAttribute("events"); List<Ticket> tickets=(List<Ticket>)request.getAttribute("tickets"); List<Review> reviews=(List<Review>)request.getAttribute("reviews"); List<String> logs=(List<String>)request.getAttribute("logs"); double totalRevenue=(Double)request.getAttribute("totalRevenue"); %>
<section class="page-head"><span class="eyebrow">Admin Control Center</span><h1>Dashboard & Analytics</h1><p>High-level oversight for events, users, bookings, reviews, and system logs.</p></section>
<section class="section">
    <div class="stats-grid">
        <div class="stat"><span><%=users.size()%></span><p>Total Users</p></div><div class="stat"><span><%=events.size()%></span><p>Total Events</p></div><div class="stat"><span><%=tickets.size()%></span><p>Total Bookings</p></div><div class="stat"><span>Rs. <%=String.format("%,.0f", totalRevenue)%></span><p>Total Sales</p></div><div class="stat"><span><%=admins.size()%></span><p>Admins / Organizers</p></div><div class="stat"><span><%=reviews.size()%></span><p>Total Reviews</p></div>
    </div>
    <div class="admin-actions"><a class="btn btn-primary" href="<%=ctx%>/add-event">Add Event</a><a class="btn btn-outline" href="<%=ctx%>/admin-register">Register Admin</a><a class="btn btn-outline" href="<%=ctx%>/financial-summary">Financial Summary</a></div>
    <div class="panel"><h2>Event Management</h2><div class="table-wrap"><table><tr><th>ID</th><th>Name</th><th>Type</th><th>Date</th><th>Venue</th><th>Action</th></tr><% for(Event e: events){ %><tr><td><%=e.getEventId()%></td><td><%=e.getEventName()%></td><td><%=e.getEventType()%></td><td><%=e.getEventDate()%></td><td><%=e.getVenueName()%></td><td><form method="post" action="<%=ctx%>/delete-event" onsubmit="return confirm('Delete event?')"><input type="hidden" name="eventId" value="<%=e.getEventId()%>"><button class="mini danger">Delete</button></form></td></tr><% } %></table></div></div>
    <div class="panel"><h2>Booking Management</h2><div class="table-wrap"><table><tr><th>Booking</th><th>User</th><th>Event</th><th>Seats</th><th>Status</th><th>Update</th></tr><% for(Ticket t: tickets){ %><tr><td><%=t.getBookingId()%></td><td><%=t.getUserId()%></td><td><%=t.getEventId()%></td><td><%=t.getSeatNo().replace(",", ", ")%></td><td><%=t.getStatus()%></td><td><form method="post" action="<%=ctx%>/update-ticket"><input type="hidden" name="bookingId" value="<%=t.getBookingId()%>"><select name="status"><option>Active</option><option>Checked-in</option><option>Cancelled</option></select><button class="mini">Save</button></form></td></tr><% } %></table></div></div>
    <div class="panel"><h2>User Management</h2><p class="muted">Only logged-in admins can edit or delete user accounts.</p><div class="table-wrap"><table><tr><th>ID</th><th>Name</th><th>Email</th><th>Phone</th><th>Password</th><th>Type</th><th>Admin Actions</th></tr><% for(User u: users){ String editFormId = "editUser" + u.getUserId(); %><tr><td><form id="<%=editFormId%>" method="post" action="<%=ctx%>/update-user"></form><input form="<%=editFormId%>" type="text" name="userId" value="<%=u.getUserId()%>" readonly></td><td><input form="<%=editFormId%>" type="text" name="fullName" value="<%=u.getFullName()%>" required></td><td><input form="<%=editFormId%>" type="email" name="email" value="<%=u.getEmail()%>" required></td><td><input form="<%=editFormId%>" type="text" name="phone" value="<%=u.getPhone()%>"></td><td><input form="<%=editFormId%>" type="text" name="password" value="<%=u.getPassword()%>" required></td><td><select form="<%=editFormId%>" name="userType"><option value="Attendee" <%= "Attendee".equalsIgnoreCase(u.getUserType()) ? "selected" : "" %>>Attendee</option><option value="User" <%= "User".equalsIgnoreCase(u.getUserType()) ? "selected" : "" %>>User</option></select></td><td class="action-cell"><button form="<%=editFormId%>" class="mini" type="submit">Save</button><form method="post" action="<%=ctx%>/delete-user" onsubmit="return confirm('Delete this user and their bookings/reviews?')"><input type="hidden" name="userId" value="<%=u.getUserId()%>"><button class="mini danger" type="submit">Delete</button></form></td></tr><% } %></table></div></div>
    <div class="panel"><h2>Activity Logs</h2><ul class="log-list"><% for(String log: logs){ %><li><%=log%></li><% } %></ul></div>
</section>
<%@ include file="footer.jsp" %>
